ALTER TABLE "Company" ADD COLUMN "planName" TEXT NOT NULL DEFAULT 'Trial';
ALTER TABLE "Company" ADD COLUMN "expiresAt" TIMESTAMP(3);
ALTER TABLE "Company" ADD COLUMN "maxUsers" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Company" ADD COLUMN "maxMessages" INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE "AiAssistantConfig" ADD COLUMN "responseMode" TEXT NOT NULL DEFAULT 'auto';
ALTER TABLE "AiAssistantConfig" ADD COLUMN "openAiApiKey" TEXT;
